OrdererOrgs:
  - Name: Orderer
    Domain: livwell.asia
    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
PeerOrgs:
  - Name: care
    Domain: care.livwell.asia
    EnableNodeOUs: true
    Template:
        Count: 2
    Users:
        Count: 1