version: '2'

volumes:
  peer0.care.livwell.asia:
  peer1.care.livwell.asia:
  orderer.livwell.asia:
  orderer2.livwell.asia:
  orderer3.livwell.asia:
  
networks:
    wellness_network:
      external:
        name: wellness_network

services:
  ca.livwell.asia:
    container_name: ca.livwell.asia
    hostname: ca.livwell.asia
    image: hyperledger/fabric-ca:$CA_IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.livwell.asia
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CSR_HOSTS=ca.livwell.asia, localhost
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.livwell.asia-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/priv_sk
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tlsca.livwell.asia-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d '
    volumes:
      - ./crypto-config/ordererOrganizations/livwell.asia/ca/:/etc/hyperledger/fabric-ca-server
      - ./crypto-config/ordererOrganizations/livwell.asia/tlsca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - wellness_network
  
  ca.care.livwell.asia:
    container_name: ca.care.livwell.asia
    hostname: ca.care.livwell.asia
    image: hyperledger/fabric-ca:$CA_IMAGE_TAG
    environment: 
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.care.livwell.asia
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server/ca.care.livwell.asia-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server/priv_sk
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/tlsca.care.livwell.asia-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d '
    volumes:
      - ./crypto-config/peerOrganizations/care.livwell.asia/ca/:/etc/hyperledger/fabric-ca-server
      - ./crypto-config/peerOrganizations/care.livwell.asia/tlsca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - wellness_network

  peer0.care.livwell.asia:
    container_name: peer0.care.livwell.asia
    hostname: peer0.care.livwell.asia
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=wellness_network
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
       # Allow more time for chaincode container to build on install.
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_ID=peer0.care.livwell.asia
      - CORE_PEER_ADDRESS=peer0.care.livwell.asia:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.care.livwell.asia:7053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.care.livwell.asia:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.care.livwell.asia:8051
      - CORE_PEER_LOCALMSPID=careMSP
      # Setting-up CouchDB as State Database
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer0.care.livwell.asia:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer0_admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=peer0_adminpw
      - CORE_METRICS_PROVIDER=prometheus
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/care.livwell.asia/peers/peer0.care.livwell.asia/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/care.livwell.asia/peers/peer0.care.livwell.asia/tls:/etc/hyperledger/fabric/tls
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
        - peer0.care.livwell.asia:/var/hyperledger/production
        - ./core.yaml:/etc/hyperledger/fabric/core.yaml
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 7051:7051
    networks:
      - wellness_network
  
  peer1.care.livwell.asia:
    container_name: peer1.care.livwell.asia
    hostname: peer1.care.livwell.asia
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=wellness_network
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
       # Allow more time for chaincode container to build on install.
      - CORE_CHAINCODE_EXECUTETIMEOUT=300s
      - CORE_PEER_ID=peer1.care.livwell.asia
      - CORE_PEER_ADDRESS=peer1.care.livwell.asia:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.care.livwell.asia:8053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.care.livwell.asia:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.care.livwell.asia:7051
      - CORE_PEER_LOCALMSPID=careMSP
      # Setting-up CouchDB as State Database
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.peer1.care.livwell.asia:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=peer1_admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=peer1_adminpw
      - CORE_METRICS_PROVIDER=prometheus
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/care.livwell.asia/peers/peer1.care.livwell.asia/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/care.livwell.asia/peers/peer1.care.livwell.asia/tls:/etc/hyperledger/fabric/tls
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
        - peer1.care.livwell.asia:/var/hyperledger/production
        - ./core.yaml:/etc/hyperledger/fabric/core.yaml
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    ports:
      - 8051:8051
    networks:
      - wellness_network

  couchdb.peer0.care.livwell.asia:
    container_name: couchdb.peer0.care.livwell.asia
    hostname: couchdb.peer0.care.livwell.asia
    image: hyperledger/fabric-couchdb:$COUCHDB_TAG
    environment:
      - COUCHDB_USER=peer0_admin
      - COUCHDB_PASSWORD=peer0_adminpw
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton3 User Interface in dev environments.
    ports:
      - "5984:5984"
    networks:
      - wellness_network
  
  couchdb.peer1.care.livwell.asia:
    container_name: couchdb.peer1.care.livwell.asia
    hostname: couchdb.peer1.care.livwell.asia
    image: hyperledger/fabric-couchdb:$COUCHDB_TAG
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=peer1_admin
      - COUCHDB_PASSWORD=peer1_adminpw
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "6984:5984"
    networks:
      - wellness_network

  orderer.livwell.asia:
    container_name: orderer.livwell.asia
    hostname: orderer.livwell.asia
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true  
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      #- GOINFO=netdns=go
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8443
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/livwell.asia/orderers/orderer.livwell.asia/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/livwell.asia/orderers/orderer.livwell.asia/tls/:/var/hyperledger/orderer/tls
        - orderer.livwell.asia:/var/hyperledger/production/orderer
    ports:
    - 7050:7050
    - 8443:8443
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    networks:
      - wellness_network
  
  orderer2.livwell.asia:
    container_name: orderer2.livwell.asia
    hostname: orderer2.livwell.asia
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true  
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      #- GOINFO=netdns=go
      - ORDERER_GENERAL_LISTENPORT=8050
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8444
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/livwell.asia/orderers/orderer2.livwell.asia/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/livwell.asia/orderers/orderer2.livwell.asia/tls/:/var/hyperledger/orderer/tls
        - orderer2.livwell.asia:/var/hyperledger/production/orderer
    ports:
    - 8050:8050
    - 8444:8444
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    networks:
      - wellness_network
  
  orderer3.livwell.asia:
    container_name: orderer3.livwell.asia
    hostname: orderer3.livwell.asia
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true  
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      #- GOINFO=netdns=go
      - ORDERER_GENERAL_LISTENPORT=9050
      - ORDERER_METRICS_PROVIDER=prometheus
      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:8445
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/livwell.asia/orderers/orderer3.livwell.asia/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/livwell.asia/orderers/orderer3.livwell.asia/tls/:/var/hyperledger/orderer/tls
        - orderer3.livwell.asia:/var/hyperledger/production/orderer
    ports:
    - 9050:9050
    - 8445:8445
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    networks:
      - wellness_network

  cli.care.livwell.asia:
    container_name: cli.care.livwell.asia
    hostname: cli.care.livwell.asia
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment: 
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.care.livwell.asia:7051
      - CORE_PEER_LOCALMSPID=careMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/care.livwell.asia/peers/peer0.care.livwell.asia/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/care.livwell.asia/peers/peer0.care.livwell.asia/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/care.livwell.asia/peers/peer0.care.livwell.asia/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/care.livwell.asia/users/Admin@care.livwell.asia/msp
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=wellness_network
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes: 
      - /var/run/:/host/var/run
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto
      - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
      - ./orderer.yaml:/etc/hyperledger/fabric/orderer.yaml
      - ./core.yaml:/etc/hyperledger/fabric/core.yaml
    depends_on:
      - ca.care.livwell.asia
      - peer0.care.livwell.asia
      - peer1.care.livwell.asia
      - couchdb.peer0.care.livwell.asia
      - couchdb.peer1.care.livwell.asia
    networks:
      - wellness_network
